### ISSUE TITLE
Parallax-bg class broken in 5.0.14

### ISSUE THREAD

**Issue by mike-adams-edd** [Office-of-Digital-Innovation/California-State-Template#103]
Hello,

I am trying to update my site to template 5.0.14 from 5.0.11 (as we will not be able to update to 5.5.x or 6 anytime soon), and I noticed that parallax is not functioning on my test site with .14 in place. There is just the empty background where the image. For reference:

Template 5.0.11: https://edd.ca.gov/
Template 5.0.14: http://134.187.115.248/

If you scroll down, you will see a section, "It's your money. Get it at CalEITC4Me." along with a button.

On the .11 site (edd.ca.gov), that photo shows up and functions just fine. On the .14 test site (134.187.115.248), there is just the gray background where the image should be. Did something happen between releases that would deprecate the parallax scrolling feature?

Thanks!

Mike Adams

**Comment by mike-adams-edd** [comment]
So I took the parallax.js section from the core js file on 5.0.11, removed all of it from my 5.0.14 .js core file and replaced it with the .11 version and it is working just fine again. So I am not sure what was changed, but it was not working with the new template.

**Comment by kkoryaka** [comment]
We posted legacy 5.0,15 release version in our releases that includes this parallax fix. Thank you for bringing it up.
