### ISSUE TITLE
v6 beta release

### ISSUE THREAD

**Issue by dben84** [Office-of-Digital-Innovation/California-State-Template#106]
Is there any estimated date when there will be production release for v6 template?

**Comment by kkoryaka** [comment]
There is no estimated date yet.

**Comment by justinsane98** [comment]
Any news on V6 release date yet?

**Comment by kkoryaka** [comment]
Our target is to release it by the end of the year. But it's not set in stone.

**Comment by dben84** [comment]
Any update on this recently? Still looking for release by the end of the year?

**Comment by kkoryaka** [comment]
Release v6 has been implemented into production.
