### ISSUE TITLE
Mobile navigation disappears in Internet Explorer

### ISSUE THREAD

**Issue by mike-adams-edd** [Office-of-Digital-Innovation/California-State-Template#107]
Hello,

During a meeting today, we noticed that mobile navigation disappears completely in mobile view on Internet Explorer. We noticed because all of the computers at EDD are set to utilize Internet Explorer as the default browser. Doing more digging, somewhere between 5.0.7 and 5.0.13, the mobile menu stopped working. edd.ca.gov still works because it is using 5.0.7, but taxes.ca.gov does not because it is using 5.0.13. Your legacy website also has the same issue, so it wasn't anything we did. My question is, what is CDT's stance on support for Internet Explorer. Looking at our analytics numbers, in the month of January 2.97% of our users were running IE in windows tablet/mobile while 8.96% of our total user base ran IE on their desktop.

Thanks so much!

Mike Adams

**Comment by kkoryaka** [comment]
Thanks for bringing it up. That is because IE is not fully supporting the flexbox. We will make this patch specifically for IE in our next legacy hot fix release.

**Comment by kkoryaka** [comment]
We just released legacy release  v5.0,16 that has this issue fixed.
https://github.com/Office-of-Digital-Innovation/California-State-Template/releases/tag/v5.0.16
