### ISSUE TITLE
jquery.validate.js

### ISSUE THREAD

**Issue by myque08** [Office-of-Digital-Innovation/California-State-Template#110]
It appears that cagov.core.js appears to interfere with adding jquery.validate.js to a form for validation. cagov.core.js throws a few errors and then $(...).validate is undefined. Do you know of a bypass for this?

**Comment by kkoryaka** [comment]
Thanks for your inquiry, I could also depend on where on the page you have placed your validation script. On this site https://covid19supplies.ca.gov/, for instance, validation script library is placed after cagov.core.js file and it works fine. Let us know if placing your script library last on the page is still throwing an error.

**Comment by kkoryaka** [comment]
State Template is now jQuery less. I will close this issue
