### ISSUE TITLE
Theme Colors Customization

### ISSUE THREAD

**Issue by coop333** [Office-of-Digital-Innovation/California-State-Template#119]
I'm with the Bureau of Automotive Repair - Department of Consumer Affairs, and we were looking into possibly making some color customization. There's a reference made on the colorscheme pages that indicates that a .less file should be available to do this. However, I cannot find this file, or instructions on how to do this. We are running version 5.0.5.

https://template.webstandards.ca.gov/sample/colorscheme-sacramento.html

It states:
"Theme Colors Customization
There are two ways to customize theme main colors. One way is to change primary and secondary theme color variables in the colorscheme-[yourcolorshceme].less file. This method will require you to re-compile the state template, you can find instructions in the readme file. After the compilation you will have updated colorscheme-[yourcolorshceme].css file.

Another way is to manually find and replace all main theme colors and their variations in colorscheme-[yourcolorshceme].css. Main theme colors classes will be listed at the top of the CSS file. You can copy their values and use find/replace feature in your web editor software to replace all those colors references with your custom colors throughout entire css file."

**Comment by kkoryaka** [comment]
Version 5.0.5 is using gulp to compile core and color scheme css files from SASS source files (It's' not LESS as you mentioned, The .less extension needs to be changed .sass in our instruction on State template website.).  Those SASS files are located inside of \source\scss folder.  Theme color variables are found in \source\scss\colorscheme folder. In your case it's colorscheme-sacramento.scss, After you customize your colors you will need to run gulp commands to compile new color scheme.  

HOW TO USE GULP:
Make sure in you website folder you have gulpfile.js, package.json files (if not please go ahead and download state Template zip file from our GiHub repository release. In your case it's [5,0,5 ](https://github.com/Office-of-Digital-Innovation/California-State-Template/releases/tag/v5.0.5)release)
- First you need to install [node.js](https://nodejs.org/en/download/) on your machine. 
- Then you need to install Gulp Globally. (run command **npm install gulp-cli -g** in your pc's PowerShell or Terminal)
- Then you need to install Gulp locally (navigate to your local website repository folder using cd command. Then use command **npm install gulp –save-dev** or **npm install gulp**
Finally, you can now use gulp task commands such as:
**gulp core** (compiles unminified cagov.core.css)
**gulp js**  (compiles unminified cagov.core.js)
**gulp dev** (compiles unminified core css js files including color schemes)
**gulp prod** (compiles minified core css and js files including color schemes)

Or in your case you can simpli compile Sacramento color scheme css file by running **gulp sacramento** or  **gulp sacramentomin**

**Comment by coop333** [comment]
I'm running into issues with version compatibility between gulp and node, and I'm also running into issues with SASS (node sass does not yet support your current environment windows 64-bit with unsupported runtime (72)). Do you know the specific versions of each (below) that were used?
Node
Gulp
SASS
Python

Also, does the latest version of the state template also use this approach?

**Comment by kkoryaka** [comment]
When I was replying initially to your issue my node version was under v12.  But after updating my node to v14 I was facing ReferenceError: primordials is not defined error when trying to run gulp. So, to fix that I had to add [npm-shrinkwrap.json](https://github.com/Office-of-Digital-Innovation/California-State-Template/blob/master/npm-shrinkwrap.json) file to my solution. After that I was able to run gulp again. Here are my versions:
Node v14.9.0
Gulp v3.9.1
SASS v6.14.8
Python v3.8

And yes, the latest version is using the same node.js and gulp commands approach to build templates core files.

**Comment by coop333** [comment]
I'm going to have take your word for it for now. I'll come back to this when I have more time.

**Comment by coop333** [comment]
Hi @kkoryaka ,

**Comment by kkoryaka** [comment]
Remove all the content from your npm-shrinkwrap.json and only fol;owing content:
{
  "dependencies": {
    "graceful-fs": {
        "version": "4.2.2"
     }
  }
}

Run npm install, It'll update npm-shrinkwrap.json with a bunch of content. Then try using gulp. Let us know if that works.

**Comment by coop333** [comment]
I got it to work! Thank you!
