### ISSUE TITLE
global-footer, invalid property value

### ISSUE THREAD

**Issue by coop333** [Office-of-Digital-Innovation/California-State-Template#121]
In the global-footer.scss file there is an appended 0 at the end of the variable (see line 9 padding-top: $line-height-computed 0;). This is causing an invalid property value warning to appear.

https://github.com/Office-of-Digital-Innovation/California-State-Template/blob/master/source/scss/cagov/global-footer.scss

**Comment by kkoryaka** [comment]
Good catch @coop333, this will be fixed in our next release.

**Comment by coop333** [comment]
Looks like this was addressed in 5.5.18.
