### ISSUE TITLE
.card-heading, .card-header

### ISSUE THREAD

**Issue by coop333** [Office-of-Digital-Innovation/California-State-Template#123]
Looks like there is a mixing of .card-heading and .card-header. In bootstrap 4 .panels were dropped and .cards were the replacement. It appears that the state template has a mixture of these classes. It seems as if some cleanup needs to happen to remove panels altogether and remove the class .card-heading (as it should be .card-header). 

See https://github.com/Office-of-Digital-Innovation/California-State-Template/blob/master/source/scss/cagov/panel.scss. 

May I suggest this be part of v6 update?

**Comment by kkoryaka** [comment]
Thank you @coop333 for bringing it up. Yes, this update should be part of v6. In our production version we are still trying to have backwards compatibility with those older bootstrap classes.
