### ISSUE TITLE
Indicate External Links

### ISSUE THREAD

**Issue by markaplet** [Office-of-Digital-Innovation/California-State-Template#124]
I have a feature request for consideration. It's helpful to have external links indicated to the user in some way. 

Perhaps an icon using a square and arrow such as this font awesome icon https://fontawesome.com/icons/external-link-square-alt?style=regular 

Similarly an icon for representing modals or popups such as this icon: https://thenounproject.com/search/?q=popup&i=849691 

My request comes with a few different approaches for consideration. 

1. Please add icons similar to those referred to above for developers to use in implementation without requiring additional web fonts.  
2. Offer an accessible mechanism for adding icons with support text to buttons and links. For example:

`<a href="http://www.google.com" target="_blank">Google 
 <span class="sr-only">Opens in new window</span>
 <i aria-hidden="true" class="ca-gov-icon-external-link"></i>
</a>`

3. Provide an option for fallback to automatically add icons such as `a:not([href*='.ca.gov']):not([href^='#']):not([href^='/']):after {...}` This approach needs work but illustrates the concept.

**Comment by kkoryaka** [comment]
Thank you @markaplet. We will definitely consider adding this feature in our next releases.

**Comment by kkoryaka** [comment]
We have added external link in our v5.5.18 release: https://template.webtools.ca.gov/sample/links.html
