### ISSUE TITLE
CDN Availibility and Fail Over

### ISSUE THREAD

**Issue by coop333** [Office-of-Digital-Innovation/California-State-Template#126]
We are updating our public website right now and we would like to solely use the CDN for referencing the state template CSS and JS. My question is, is this foolish? Should we have a failover to a local library? This also brings up the question, what is the availability of your CDNs? Looking at the bigger companies they use multiple CDNs for failover (not a local copy on the web server). I have many topics on how to failover, but there are usually comments below those failover strategies of "why failover?". It seems that the availability of CDNs these days are a lot better than say 8 years ago when a lot of those articles were written.

Any help is appreciated.

**Comment by kkoryaka** [comment]
Our Azure CDN service is pretty dependable. Such high visibility and high profile websites as ca.gov, response.ca.gov are using Azure CDN without any failover. In my days here CDN failure never happened.

**Comment by coop333** [comment]
Thank you so much for the quick response.
