### ISSUE TITLE
Use of i tag for icon block

### ISSUE THREAD

**Issue by coop333** [Office-of-Digital-Innovation/California-State-Template#127]
I'm using the icon blocks example found on this page - https://template.webstandards.ca.gov/sample/icon-blocks.html and I'm receiving an issue from SiteImprove accessibility checker. The issue is:

> ### A - 1.3.1 Info and Relationships - 'i' tag used to format text
> 
> The italics-tag 'i' is used to highlight text.
> 
> Consider the following:
> 
> If the text should be emphasized semantically, use the 'emphasize' tag instead.
> 
> If the text is a heading, an H-tag (such as H1, H2, H3...) should be used instead.
> 
> If the text is highlighted as a visual effect, CSS should be used to do this.
> 
> **Please note that even though 'i' tags are commonly used for inserting icons, this is considered bad practice.**

I tried to perform a workaround here, but anytime I use anything other than an i tag for the icon the icon appears at the top of the circle instead of the middle. Here's my code:

        <div class="group">
            <div class="col-md-12 pb-3">
                
                <div class="group p-t-60">
                    <div class="row row-eq-height justify-content-center">
                        <div class="col-md-3 shadow2 section-default text-center ml-3 mr-3 p-b-lg">
                            
                            <span class="icon-block bg-primary-gradient rounded-50x">
                                <i class="ca-gov-icon-road-pin"></i>
                            </span>
                            <h2 class="h4 m-b-sm">Program Information</h2>
                            <p class="m-b">Learn about the California Smog Check Program</p>
                            <span><a class="text-uppercase font-size-sm" href="/pdf/Smog_Check_Brochure.pdf">English</a></span>
                            &nbsp;/&nbsp;
                            <span><a class="text-uppercase font-size-sm" href="/pdf/Smog_Check_Brochure_Spanish.pdf">Español</a></span>
                            
                        </div>
                        <div class="col-md-3 shadow2 section-primary text-center ml-3 mr-3 p-b-lg">
                            
                            <span class="icon-block bg-primary-gradient rounded-50x">
                                <i class="ca-gov-icon-location"></i>
                            </span>
                            <h2 class="h4 m-b-sm">Find a Station</h2>
                            <p class="m-b">Use our Auto Shop Locator to find a Smog Check station near you</p>
                            <a class="text-uppercase font-size-sm" href="/services/ARD/Search">Auto Shop Locator</a>
                            
                        </div>
                        <div class="col-md-3 shadow2 section-understated text-center ml-3 mr-3 p-b-lg">
                            
                            <span class="icon-block bg-primary-gradient rounded-50x">
                                <i class="ca-gov-icon-question-fill"></i>
                            </span>
                            <h2 class="h4 m-b-sm">Frequently Asked Questions</h2>
                            <p class="m-b">Find answers to questions on requirements, results, inspections issues, and more</p>
                            <a class="text-uppercase font-size-sm" href="/Consumer/California_Smog_Check_Program/FAQs">Smog Check FAQ</a>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>

Any help is appreciated.

**Comment by kkoryaka** [comment]
Thanks for bringing it up. We will fix it in our next release. In the meantime you can try using <span> instead of <i> but you need to add following css styles to it to make sure it's centered vertically.
`  position: relative;
    top: 50%;
    transform: translateY(-50%);
    display: block;`

**Comment by coop333** [comment]
Thank you @kkoryaka.
