### ISSUE TITLE
Mixed Content Error on serp.html

### ISSUE THREAD

**Issue by coop333** [Office-of-Digital-Innovation/California-State-Template#133]
On the serp.html example page there is a reference to a google css file via http. It doesn't appear that this css file exists and loading it as-is is causing a mixed content error in the console. 
https://github.com/Office-of-Digital-Innovation/California-State-Template/blob/master/serp.html

**Comment by kkoryaka** [comment]
Thanks! We will fix it with our latest jQuery-less version 5.6.0

**Comment by kkoryaka** [comment]
This is now fixed.
