### ISSUE TITLE
Timeline Component Structure

### ISSUE THREAD

**Issue by markaplet** [Office-of-Digital-Innovation/California-State-Template#140]
I believe the the structure of the new [Timeline component](https://beta.template.webtools.ca.gov/sample/timeline.html) is not structured correctly. There are a few things that I think could be improved for assistive technology.

I believe the `article` element should wrap the content on both the left and right side of the line/dot. The information is all together and would make less sense individually. 

The headings are also out of order. In the first row. "Project Manager" is an h4, "2016 - Current" is an h5, then finally "State of California" is an h3. This is especially confusing in a screen reader because it appears that "Full Stack Developer" (h4) and "2014 - 2016" (h5) from the second row are semantically connected when they are not. The hierarchy and the intended relationships have been broken. This is a little easier to visualize using WAVE then viewing the "Structure" tab. 

My recommendation would be as follows:

1. Wrap both and left columns in an article 
2. Move _Timeline Content_ before _Timeline Date_ and use bootstraps styles to maintain the look currently established.

**Comment by kkoryaka** [comment]
This is great stuff, @markaplet. We will try to incorporate your suggested structural improvements to this component in our next State Template revision.

**Comment by kkoryaka** [comment]
This issue was fixed in 5.6.1 release. Closing this issue
