### ISSUE TITLE
CA.gov logo, dropdown borders, nav hover

### ISSUE THREAD

**Issue by WebmasterJ** [Office-of-Digital-Innovation/California-State-Template#15]
I've seen the following errors with the update; otherwise the colors look great (I haven't checked them for AAA compliance, but they appear to be a significant improvement):

Corrects the issue of centered hovering on the yellow line (right below main nav):

  .megadropdown .nav-arrow-down {
    margin-left: -65px;                               /* Modified to "-50px" */
  }

Re-adds the borders for the sub-nav elements of the main nav:

.second-level-nav > li {
  border: 1px solid;
  border-left-color: #d6d6d6;
}

**Comment by kkoryaka** [comment]
Could you provide the screenshots of the issues? Our latest template is posted here: http://beta.template.webtools.ca.gov/.  This is where the latest changes. Can you replicate the issues there?
