### ISSUE TITLE
Ca

### ISSUE THREAD

**Issue by Jacobtarango21** [Office-of-Digital-Innovation/California-State-Template#161]
__Originally posted by @Jacobtarango21 in https://github.com/Code52/saywat/issues/21__

**Comment by Jacobtarango21** [comment]
![image](https://user-images.githubusercontent.com/58198765/132448562-2301f504-fa7c-4852-a674-f50a5668a155.png)

**Comment by kkoryaka** [comment]
Not sure if this issue is State Template related.
