### ISSUE TITLE
Bambinton

### ISSUE THREAD

**Issue by CDSS-Jansson** [Office-of-Digital-Innovation/California-State-Template#165]
![image](https://user-images.githubusercontent.com/87678482/138365320-eec8d12f-25e0-475e-ba39-452173e1e50a.png)

Personally, I'll refer to it as bambinton from now on. 

Professionally, I recommend we rename this to "ca-gov-icon-badminton".

Also, would it be possible to add a trash can?

**Comment by kkoryaka** [comment]
Good catch, @CDSS-Jansson, we will try to fix this typo in our next State Template revision. And yes, good suggestion, we will add trash can.

**Comment by kkoryaka** [comment]
This issue was fixed in 5.6.1 release. Closing the issue
