### ISSUE TITLE
Negative border-radius value

### ISSUE THREAD

**Issue by markaplet** [Office-of-Digital-Innovation/California-State-Template#185]
The "Card" component was found to have a negative value for the border-radius. Only positive values or 0 are valid for this property.

Example from line 20124 of [cagov.core.css ](https://github.com/Office-of-Digital-Innovation/California-State-Template/blob/93192a84a5b342d42e9fcb178aa509a9b038dbbb/css/cagov.core.css#L21025)

`.card-header:first-child {
  border-radius: -1px -1px 0 0;
}`

**Comment by kkoryaka** [comment]
This issue was fixed in 5.6.1 release. Closing the issue
