### ISSUE TITLE
Slideshow Banner Controls on Mobile

### ISSUE THREAD

**Issue by markaplet** [Office-of-Digital-Innovation/California-State-Template#59]
in v5.0.7 of the template, the `.header-slideshow-banner` controls for slide number and play/pause buttons can overlap text on some small screens. Adding a media breakpoint for xs screens and positioning the `.banner-pager` and `.banner-play-pause` to the top ~20px fixes the issue.

**Comment by kkoryaka** [comment]
This is addressed in our latest production release. Thanks for you input.
