### ISSUE TITLE
Grid .quarter not responsive

### ISSUE THREAD

**Issue by markaplet** [Office-of-Digital-Innovation/California-State-Template#60]
The grid value `.quarter` does not apply useful responsive for small screens. 

**Current Usage** 
`.quarter {
    @include make-sm-column(6);
    @include make-sm-column(3);
}`

**Suggested Alternative inline with v4**
`.quarter {
    @include make-xs-column(6);    // make 2 column on extra small and small 
    @include make-md-column(3);    // 4 column on medium and up
}`

**Bootstrap'ish Grid**
`.quarter {
    @include make-xs-column(12);    // full width on xs screens
    @include make-sm-column(6);    // 2 column on small screens
    @include make-md-column(3);   // 4 column on medium and up
}`

**Comment by kkoryaka** [comment]
This is addressed in our latest v5.0.8 release. We've used your suggested alternative. Thanks you for your input.
