### ISSUE TITLE
v5.0.12 / v5.5.9

### ISSUE THREAD

**Issue by dben84** [Office-of-Digital-Innovation/California-State-Template#88]
In the release notes for v5.0.12, I noticed that some of the same updates are listed under v5.5.9 (beta). Are there improvements to these 4 items, or are they carried over to 5.5.9 with just new icons in the beta release? What other updates are planning for next production release?

**Comment by kkoryaka** [comment]
You are right, some of 5.0 Improvements/fixes are carried over to v5.5 and vise versa because those fixes are applicable to both. In our next release we will make v5.5 a production release. Also, we will publish v6 as our new beta.

**Comment by dben84** [comment]
Thanks - sounds like it's best to wait for v5.5 production release then, since I've been looking for those accessibility fixes specifically. Still planned for January?

**Comment by kkoryaka** [comment]
Yes, we are aiming for January.

**Comment by kkoryaka** [comment]
Version 5.5 is now production
