### ISSUE TITLE
Tab Panels, Accordions and screen readers

### ISSUE THREAD

**Issue by mike-adams-edd** [Office-of-Digital-Innovation/California-State-Template#94]
Hello,

Before implementing the latest template on our website, I decided to test out the updates to the screen reader issue I had using the template website. While the content is now read by a screen reader (using both JAWS and NVDA) if you hover over that content with a mouse, it is not read at all still if you are navigating just using your keyboard (which is what those with visual disabilities are likely to do). When navigating with a keyboard, it will just tell you which tab panel you are in, and if an accordion is expanded. Is there a way to force the focus into that content making the screen reader then read the expanded content?

Also, I have tested this on my machine, and had one of my accessibility team members test on their machine with the same results, making the content inaccessible still.

Thanks in advance!

Mike Adams

**Comment by kkoryaka** [comment]
Thank you for your inquiry. I just tried to hover over the accordion content on this page http://template.webtools.ca.gov/sample/accordions.html with my cursor and I was able to hear the expanded accordion content that was read by NVDA without any issues. I think the key is what screen reader mode you are using. I have noticed that it behaves  similar to what you have described In focus mode. But in browse mode I am able sequentially go from one html item to another using keyboard or cursor and I am able to hear the content. If you feel that we need to examine this issue more closely with you please send us your contact  to Info.Eservices@state.ca.gov and will discuss this issue in greater details.

**Comment by kkoryaka** [comment]
New release has a new tabs module that uses focus into the tab's content approach. http://template.webtools.ca.gov/sample/tabs.html

**Comment by mike-adams-edd** [comment]
Hello,

Thank you for getting that new tab field in place, I just tested it with JAWS and NVDA and it works very well. I did want to discuss the accordions though. Can we get something similar for the accordions? As I mentioned, if you hover over the accordions when they are expanded it will read the content, but those with visual impairments are not utilizing a mouse. They are utilizing keyboard navigation, and when you do use keyboard navigation, the content is not read in the expanded fields.

I am hoping you can modify they existing accordions to function like the tab panels, as we have a LOT of accordions on the EDD website.

Thanks!

Mike Adams

**Comment by mike-adams-edd** [comment]
Hello, I am just following up on my reply as I have not heard back about it.

Thanks!

Mike Adams

**Comment by kkoryaka** [comment]
We will try to incorporate similar keyboard navigation approach to the accordion as we did to the tabs in our next release.

**Comment by mike-adams-edd** [comment]
Hey there,

What accordions are you utilizing on https://webstandards.ca.gov/accessibility/ as those are fairly friendly. But they are different than the ones you all provide in the examples page.

Thanks!

**Comment by kkoryaka** [comment]
That is WordPress site. It uses divi theme accordion modules, However, those modules use extra accessibility js plugin.

**Comment by mike-adams-edd** [comment]
Hello again,

I wanted to see if there was any chance of getting this fix implemented on the 5.0.x template, as we will not be able to upgrade to the 5.5.x template for quite a while (possibly a year or so). As this was an issue brought up with this template, I am truly hoping so.

Thanks again!

Mike Adams

**Comment by kkoryaka** [comment]
We have released v5.0.15 (Legacy Release) that have this fix for you. Also, added this fix in our production release (5.5.12)
